inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - ".git/**/*"
    - "public/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "test/**/*"
    - "spec/**/*"
    - "node_modules/**/*"
    - "bin/**"
    - "Gemfile"
    - "Rakefile"
    - "app/channels/**/*"
    - "vendor/**/*"

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/MutableConstant:
  Enabled: false
StringLiterals:
  EnforcedStyle: single_quotes
Metrics/MethodLength:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
Style/GuardClause:
  Enabled: false